name: Build
on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        arch: [x86_64]
        include:
          - os: macos-13
            arch: arm64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          # Linux
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_ENVIRONMENT_LINUX: OMPL_BUILD_TARGET="linux" OMPL_BUILD_ARCH="${{ matrix.arch }}"
          # OS X
          CIBW_ENVIRONMENT_MACOS: OMPL_BUILD_TARGET="macos" OMPL_BUILD_ARCH="${{ matrix.arch }}"
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
            # All systems
          CIBW_BEFORE_ALL: ./before_all.sh
          CIBW_BEFORE_BUILD: ./before_build.sh
          CIBW_BUILD: cp3{10,11,12}-macosx_{x86_64,arm64} cp3{9,10,11,12}-manylinux_x86_64
          CIBW_BUILD_VERBOSITY: 1
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse

  pre-release:
    name: Pre Release
    concurrency:
      group: push-${{ github.ref_name }}-prerelease
      cancel-in-progress: true
    needs: [build_wheels]
    runs-on: "ubuntu-latest"
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: prerelease
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse

      # Create the actual prerelease
      # https://github.com/ncipollo/release-action
      - name: GitHub Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          tag: "prerelease"
          name: "Development Build"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: "wheelhouse/*"
